// Package block reads and writes the gignore-managed region of a .gitignore.
//
// gignore owns only the lines between its start and end markers. Everything
// before and after them belongs to the user and is written back unchanged, so
// regenerating never loses hand-written rules.
package block

import (
	"errors"
	"fmt"
	"strings"
)

const (
	startPrefix = "# >>> gignore start"
	endMarker   = "# <<< gignore end"
	noteLine    = "# Generated by gignore. Edits inside this block are replaced on update; add your own rules outside it."
	userHeader  = "# Project-specific rules (gignore keeps everything outside the block above)"
)

// ErrMalformed means a start marker has no matching end marker.
var ErrMalformed = errors.New("gignore block has a start marker but no end marker")

// Doc is a .gitignore split around the managed block.
type Doc struct {
	Before    string   // text before the start marker
	Body      string   // generated rules between the note line and the end marker
	After     string   // text after the end marker
	Templates []string // template keys recorded in the start marker
	Found     bool     // a complete block exists
	CRLF      bool     // the file uses Windows line endings
}

// Parse splits content around the first managed block.
func Parse(content string) (Doc, error) {
	d := Doc{CRLF: strings.Contains(content, "\r\n")}
	content = strings.ReplaceAll(content, "\r\n", "\n")
	lines := strings.Split(content, "\n")
	start, end := -1, -1
	for i, l := range lines {
		t := strings.TrimSpace(l)
		if start < 0 && strings.HasPrefix(t, startPrefix) {
			start = i
			continue
		}
		if start >= 0 && t == endMarker {
			end = i
			break
		}
	}
	if start < 0 {
		d.Before = content
		return d, nil
	}
	if end < 0 {
		d.Before = content
		return d, ErrMalformed
	}
	d.Found = true
	d.Templates = parseStart(lines[start])
	bodyStart := start + 1
	if bodyStart < end && strings.TrimSpace(lines[bodyStart]) == noteLine {
		bodyStart++
	}
	d.Before = strings.Join(lines[:start], "\n")
	d.Body = strings.Join(lines[bodyStart:end], "\n")
	d.After = strings.Join(lines[end+1:], "\n")
	return d, nil
}

func parseStart(line string) []string {
	_, rest, ok := strings.Cut(line, ":")
	if !ok {
		return nil
	}
	return strings.FieldsFunc(rest, func(r rune) bool { return r == ',' || r == ' ' || r == '\t' })
}

// Render builds a complete block for the given template keys and rules.
func Render(keys []string, body string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s: %s\n", startPrefix, strings.Join(keys, ", "))
	b.WriteString(noteLine + "\n")
	b.WriteString(strings.TrimRight(body, "\n"))
	b.WriteString("\n" + endMarker + "\n")
	return b.String()
}

// Mode picks how Apply combines the block with an existing file.
type Mode int

const (
	// Merge replaces an existing block, or puts a new one above existing rules.
	Merge Mode = iota
	// Replace discards the existing file and writes only the block.
	Replace
)

// Apply returns the new file content with block placed into existing.
//
// A new block goes at the top of the file so the user's own rules, which come
// later, can override template rules (later patterns win in .gitignore).
func Apply(existing, blk string, mode Mode) (string, error) {
	d, err := Parse(existing)
	if err != nil && mode != Replace {
		return "", err
	}
	var out string
	switch {
	case mode == Replace || strings.TrimSpace(existing) == "":
		out = blk + "\n" + userHeader + "\n"
	case d.Found:
		out = joinParts(d.Before, blk, d.After)
	default:
		out = blk + "\n" + userHeader + "\n" + strings.TrimLeft(d.Before, "\n")
	}
	out = strings.TrimRight(out, "\n") + "\n"
	if d.CRLF {
		out = strings.ReplaceAll(out, "\n", "\r\n")
	}
	return out, nil
}

func joinParts(before, blk, after string) string {
	var b strings.Builder
	if before != "" {
		b.WriteString(before)
		b.WriteString("\n")
	}
	b.WriteString(blk)
	b.WriteString(after)
	return b.String()
}

// Remove deletes the managed block and returns the remaining content.
func Remove(existing string) (string, bool, error) {
	d, err := Parse(existing)
	if err != nil || !d.Found {
		return existing, false, err
	}
	rest := joinParts(d.Before, "", d.After)
	rest = strings.Replace(rest, userHeader+"\n", "", 1)
	rest = strings.TrimLeft(rest, "\n")
	if strings.TrimSpace(rest) != "" {
		rest = strings.TrimRight(rest, "\n") + "\n"
	}
	if d.CRLF {
		rest = strings.ReplaceAll(rest, "\n", "\r\n")
	}
	return rest, true, nil
}

// BodyLineOffset returns the 0-based line in the full file where Body starts,
// so callers can map a file line number back to a template section.
func (d Doc) BodyLineOffset() int {
	n := 0
	if d.Before != "" {
		n = strings.Count(d.Before, "\n") + 1
	}
	return n + 2 // start marker + note line
}
